name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install PostgreSQL packages - 1
      run: sudo apt install postgresql-common
    - name: install PostgreSQL packages - 2
      run: sudo apt install postgresql-server-dev-16
    - name: install llvm, to build the stencils
      run: sudo apt install llvm clang
    - name: make
      run: make
